In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

import nltk #language processing
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.corpus import stopwords

#import re
#import emoji

data_train = pd.read_csv("congressional_tweet_training_data.csv",names=None)
data_test= pd.read_csv("congressional_tweet_test_data.csv",names=None)

In [2]:
data_train

,favorite_count,full_text,hashtags,retweet_count,year,party_id
0,0,"b""RT @KUSINews: One of our longtime viewers wa...",KUSI,10,2017.0,R
1,258,"b""Today I'm urging the @CDCgov to immediately ...",Coronavirus,111,2020.0,R
2,0,"b'Tomorrow, #MO03 seniors graduate from Calvar...",MO03,2,2014.0,R
3,9,b'Congrats to #TeamUSA and Canton Native @JGre...,TeamUSA WorldJuniors,3,2017.0,R
4,3,b'Pleased to support @amergateways at their Ju...,ImmigrantHeritageMonth,3,2019.0,D
...,...,...,...,...,...,...
592798,3,"b'This time, it focused on careers in #publics...",publicservice publicsafety,0,2017.0,R
592799,5,"b'.#StormyDaniels, #MichaelWolfe, #JamesComey ...",StormyDaniels MichaelWolfe JamesComey,1,2018.0,R
592800,33,b'@NRDems The American people deserve the trut...,CultureOfCorruption,14,2020.0,D
592801,4,b'Only 2 weeks left to submit your #app to the...,app copolitics CAC16 HouseOfCode co06,3,2016.0,R
592802,155,b'The #MuslimBan remains as un-American and of...,MuslimBan,48,2020.0,D

In [3]:
data_train['party_class']=data_train['party_id'].apply(lambda x: 0 if x=='D' else 1)

In [4]:
data_train

,favorite_count,full_text,hashtags,retweet_count,year,party_id,party_class
0,0,"b""RT @KUSINews: One of our longtime viewers wa...",KUSI,10,2017.0,R,1
1,258,"b""Today I'm urging the @CDCgov to immediately ...",Coronavirus,111,2020.0,R,1
2,0,"b'Tomorrow, #MO03 seniors graduate from Calvar...",MO03,2,2014.0,R,1
3,9,b'Congrats to #TeamUSA and Canton Native @JGre...,TeamUSA WorldJuniors,3,2017.0,R,1
4,3,b'Pleased to support @amergateways at their Ju...,ImmigrantHeritageMonth,3,2019.0,D,0
...,...,...,...,...,...,...,...
592798,3,"b'This time, it focused on careers in #publics...",publicservice publicsafety,0,2017.0,R,1
592799,5,"b'.#StormyDaniels, #MichaelWolfe, #JamesComey ...",StormyDaniels MichaelWolfe JamesComey,1,2018.0,R,1
592800,33,b'@NRDems The American people deserve the trut...,CultureOfCorruption,14,2020.0,D,0
592801,4,b'Only 2 weeks left to submit your #app to the...,app copolitics CAC16 HouseOfCode co06,3,2016.0,R,1
592802,155,b'The #MuslimBan remains as un-American and of...,MuslimBan,48,2020.0,D,0

In [5]:
data_train.dropna(subset=['full_text'],inplace=True) #First, I drop the rows with NA in the text column
data_train

,favorite_count,full_text,hashtags,retweet_count,year,party_id,party_class
0,0,"b""RT @KUSINews: One of our longtime viewers wa...",KUSI,10,2017.0,R,1
1,258,"b""Today I'm urging the @CDCgov to immediately ...",Coronavirus,111,2020.0,R,1
2,0,"b'Tomorrow, #MO03 seniors graduate from Calvar...",MO03,2,2014.0,R,1
3,9,b'Congrats to #TeamUSA and Canton Native @JGre...,TeamUSA WorldJuniors,3,2017.0,R,1
4,3,b'Pleased to support @amergateways at their Ju...,ImmigrantHeritageMonth,3,2019.0,D,0
...,...,...,...,...,...,...,...
592798,3,"b'This time, it focused on careers in #publics...",publicservice publicsafety,0,2017.0,R,1
592799,5,"b'.#StormyDaniels, #MichaelWolfe, #JamesComey ...",StormyDaniels MichaelWolfe JamesComey,1,2018.0,R,1
592800,33,b'@NRDems The American people deserve the trut...,CultureOfCorruption,14,2020.0,D,0
592801,4,b'Only 2 weeks left to submit your #app to the...,app copolitics CAC16 HouseOfCode co06,3,2016.0,R,1
592802,155,b'The #MuslimBan remains as un-American and of...,MuslimBan,48,2020.0,D,0

In [6]:
data_train=data_train.reset_index(drop=True) #to fix the indices

In [7]:
data_test['party_class']=data_test['party'].apply(lambda x: 0 if x=='D' else 1)

In [8]:
data_test

,Id,favorite_count,full_text,hashtags,retweet_count,year,party,party_class
0,0,70,b'#TaxReform improved the playing field for Am...,TaxReform,13,2018.0,D,0
1,1,27,"b'This #NativeWomensEqualPay Day, we recommit ...",NativeWomensEqualPay,11,NaN,D,0
2,2,49,"b""\xe2\x80\x9cI became convinced that our gene...",MeToo ShatteringTheSilence,24,2017.0,D,0
3,3,14,"b'During #NationalAdoptionMonth, we honor the ...",NationalAdoptionMonth,2,2019.0,D,0
4,4,13,b'Happy #AirborneDay to our @USArmy paratroope...,AirborneDay AirborneAllTheWay,7,2018.0,D,0
...,...,...,...,...,...,...,...,...
264995,264995,516,b'We need to #ExtendCHIP before a single child...,ExtendCHIP,223,2017.0,D,0
264996,264996,0,"b""Our #ObamaCare investigation continued today...",ObamaCare,3,2013.0,D,0
264997,264997,1,b'Congratulations to the new #MissTeenUSA Loga...,MissTeenUSA CT,4,2012.0,D,0
264998,264998,2174,b'Speaking of dishonesty. Nothing like being c...,mosen,1168,2018.0,D,0
264999,264999,6,"b'In honor of #ConstitutionDay, we remember th...",ConstitutionDay,3,2015.0,D,0

In [9]:
text=data_train['hashtags'] 
text2=data_test['hashtags']

In [10]:
frames = [text, text2]
  
result = pd.concat(frames)
display(result)

0                           KUSI
1                    Coronavirus
2                           MO03
3           TeamUSA WorldJuniors
4         ImmigrantHeritageMonth
                   ...
264995                ExtendCHIP
264996                 ObamaCare
264997            MissTeenUSA CT
264998                     mosen
264999           ConstitutionDay
Name: hashtags, Length: 857803, dtype: object

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()
X=tfidf.fit_transform(result)

In [12]:
X_train=X[0:592803]
y_train=data_train['party_class']
X_test=X[592803:857803]

Naive Bayes

In [13]:
from sklearn.naive_bayes import MultinomialNB

In [14]:
X_train=X[0:592803]
y_train=data_train['party_class']
X_test=X[592803:857803]

In [15]:
clf2=MultinomialNB()

In [16]:
clf2.fit(X_train,y_train)

MultinomialNB()

In [17]:
y_test=clf2.predict(X_test)

In [18]:
y_test

array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

In [19]:
y_test=pd.DataFrame(data=y_test, columns=['party'])

In [20]:
y_test['party']=y_test['party'].apply(lambda x: 'D' if x==0 else 'R')

In [21]:
y_test

       party
0          R
1          D
2          D
3          R
4          R
...      ...
264995     D
264996     R
264997     D
264998     R
264999     R

[265000 rows x 1 columns]

In [23]:
y_test.to_csv('ytest_nb_hashtag_istanbul.csv')

Source: https://iq.opengenus.org/naive-bayes-on-tf-idf-vectorized-matrix/